# Generated by Django 2.1.7 on 2019-04-08 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientregistrationform',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('client_telephone', models.CharField(max_length=15)),
                ('client_contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('client_contact_telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('client_service', models.CharField(max_length=20)),
                ('client_digital_address', models.CharField(blank=True, max_length=20, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientregistrationform',
                'managed': True,
            },
        ),
    ]
