# Generated by Django 2.1.7 on 2019-03-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientregistrationform',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('client_username', models.CharField(max_length=50)),
                ('client_telephone', models.CharField(max_length=15)),
                ('client_contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('client_contact_telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('client_email', models.CharField(max_length=20)),
                ('client_service', models.CharField(max_length=20)),
                ('client_digital_address', models.CharField(blank=True, max_length=20, null=True)),
                ('client_password', models.TextField()),
                ('time_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'clientregistrationform',
            },
        ),
    ]
